#include "../../../LIB/BS_LIB.h"
#include "sput.h"
#include "general_dsl.h"

void general_test_1();
void general_test_2();
void general_test_3();
void general_test_4();
void general_test_5();
void general_test_6();
void general_test_7();
void general_test_8();
void general_test_9();
void general_test_10();
void general_test_11();
void general_test_12();
void general_test_13();
void general_test_14();
void general_test_15();
void bit_seq_extraction_test_16();
void bit_seq_arith_test_17();
void bs_seq_mult_test_18();
void bs_bit_cast_test_19();
