#include "led.h"
void cipher_constant_time();
void cipher_time();
void addConstants_time();
void subCells_time();
void shift_row_time();
void gm_mult_time();
void MixColumnSerial_time();
void single_run();
